### ISSUE TITLE
Any plans for another release, maybe even non-alpha?

### ISSUE THREAD

**Issue by jurgenhaas** [albertofem/rsync-lib#23]
It looks like this library is fairly stable and it deserves another release since the latest alpha is over 2,5 years old. Maybe even a beta or a 1.0 release tag? I wonder why not.

**Comment by jurgenhaas** [comment]
@albertofem any chance of getting a release published?

**Comment by albertofem** [comment]
Hey there! Sorry for the late response!

Yes, I agree we should release a stable 1.0.0 version. Let me blow the dust off the library a little bit and I'll come back to you soon.

**Comment by jurgenhaas** [comment]
Sounds great, thanks a lot.

**Comment by albertofem** [comment]
1.0.0 released!
