### ISSUE TITLE
I'm having an issue while include the project.

### ISSUE THREAD

**Issue by satheesh110** [albertofem/rsync-lib#9]
I'm new to the php classes. I couldn't include the file properly inside my existing project. I have no idea, what are all the file necessary to use rsync. Please someone help me.

[UPDATE]
Any how I managed to bringing all classes together and run it. But rsync isn't really happening. 
Final command being formed by the class is.
"ssh -i '/homt/satheesh/.ssh/id_milanity.pub'/usr/bin/rsync -a --delete --rsh 'ssh -i 'id_milanity.pub'' /var/www/html/PROJECT/ cecots@192.168.1.222:/home/cecots/Backup/web/www/"

I tried to run this on the terminal and met a warning
"Warning: Identity file /homt/satheesh/.ssh/id_milanity.pub/usr/bin/rsync not accessible: No such file or directory."
AND

"unknown option -- -"

Please help me

**Comment by albertofem** [comment]
Closing as too old. If you still have this problem please open a new issue with more information (for example, a code snippet, platform, etc.)
